from odoo import api, fields, models


class SaleOrderPiHistory(models.Model):
    _name = "sale.order.pi.history"
    _description = "Proforma Invoice History"
    _order = "create_date desc"

    sale_order_id = fields.Many2one(
        "sale.order",
        string="Sale Order",
        required=True,
        ondelete="cascade",
        index=True,
    )
    name = fields.Char(string="Reference", required=True, copy=False)
    summary = fields.Text(string="Summary")
    full_amount = fields.Float(
        string="Full Order Amount",
        help="Total order amount at the time this PI was generated.",
    )
    amount = fields.Float(string="Amount Printed")
    qty = fields.Float(string="Qty Printed")
    payment_percentage = fields.Selection(
        [
            ("25", "25%"),
            ("50", "50%"),
            ("75", "75%"),
            ("custom", "Custom"),
        ],
        string="Payment %",
    )
    user_id = fields.Many2one(
        "res.users",
        string="Generated By",
        default=lambda self: self.env.user,
        readonly=True,
    )